install.packages("dplyr")
library("dplyr")
install.packages("ggplot2")
library("ggplot2")
install.packages("ggpubr")
library("ggpubr")
install.packages("readxl")
library("readxl")
install.packages("ggpubr")
library("ggpubr")
library(tidyverse)
library(broom)
install.packages("mctest")
library(mctest)
library(investr)
library(robustbase)
library(tidyverse)
install.packages("caret")
library(caret)
install.packages("corrplot")
library(corrplot)

oscarsDF <- data.frame(read.csv("C:\\Users\\smuke\\Downloads\\the_oscar_award.csv"))
movieDf <- data.frame(read.csv("C:\\Users\\smuke\\Downloads\\movie_industry.csv"))
numericMoveDF <- movieDf %>% select(budget, gross, runtime, score, votes, year)
numericMoveDF$netrevenue <- numericMoveDF$gross - numericMoveDF$budget
corMovieDF <- cor(numericMoveDF, method = c("pearson", "kendall", "spearman"))
corrplot(corMovieDF, method="pie")
fit <- lm(netrevenue ~ score + votes, data = numericMoveDF)

plot(fit)
summary(fit)
fit2 <- lm(gross ~  budget, data = movieDf)
plot(fit2)
summary(fit2)
